/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.CaixaDao;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import regrasDeNegocios.Caixa;

/**
 *
 * @author letic
 */
public class FormCaixa extends javax.swing.JDialog {

    /**
     * Creates new form FormCaixa
     */
    public FormCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon("logo-ifro.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btAbrirCaixa1 = new javax.swing.JButton();
        btEditar1 = new javax.swing.JButton();
        btExcluirCaixa1 = new javax.swing.JButton();
        btFecharCaixa1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btOk1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_caixa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1Fundo = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(635, 480));
        setMinimumSize(new java.awt.Dimension(635, 480));
        setPreferredSize(new java.awt.Dimension(635, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        btAbrirCaixa1.setBackground(new java.awt.Color(117, 64, 15));
        btAbrirCaixa1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAbrirCaixa1.setForeground(new java.awt.Color(255, 255, 255));
        btAbrirCaixa1.setText("Abrir Caixa");
        getContentPane().add(btAbrirCaixa1);
        btAbrirCaixa1.setBounds(10, 370, 140, 43);

        btEditar1.setBackground(new java.awt.Color(117, 64, 15));
        btEditar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btEditar1.setForeground(new java.awt.Color(255, 255, 255));
        btEditar1.setText("Editar");
        btEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btEditar1);
        btEditar1.setBounds(160, 370, 140, 43);

        btExcluirCaixa1.setBackground(new java.awt.Color(117, 64, 15));
        btExcluirCaixa1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btExcluirCaixa1.setForeground(new java.awt.Color(255, 255, 255));
        btExcluirCaixa1.setText("Excluir");
        getContentPane().add(btExcluirCaixa1);
        btExcluirCaixa1.setBounds(320, 370, 140, 43);

        btFecharCaixa1.setBackground(new java.awt.Color(117, 64, 15));
        btFecharCaixa1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btFecharCaixa1.setForeground(new java.awt.Color(255, 255, 255));
        btFecharCaixa1.setText("Fechar Caixa");
        getContentPane().add(btFecharCaixa1);
        btFecharCaixa1.setBounds(470, 370, 150, 43);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisar:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 140, 30);

        btOk1.setBackground(new java.awt.Color(117, 64, 15));
        btOk1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btOk1.setForeground(new java.awt.Color(255, 255, 255));
        btOk1.setText("OK");
        getContentPane().add(btOk1);
        btOk1.setBounds(550, 60, 70, 30);

        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 60, 390, 30);

        jT_caixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Data Abertura", "Saldo Inicial", "Valor Créditos", "Valor Débitos", "Saldo Final", "Status Caixa", "Data Fechamento"
            }
        ));
        jScrollPane3.setViewportView(jT_caixa);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 110, 610, 230);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Caixa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 10, 112, 44);

        jLabel1Fundo.setBackground(new java.awt.Color(117, 64, 15));
        jLabel1Fundo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\facat.png")); // NOI18N
        jLabel1Fundo.setText("CAIXAAA");
        getContentPane().add(jLabel1Fundo);
        jLabel1Fundo.setBounds(0, 0, 630, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditar1ActionPerformed
    
    public void preencherTabela(){
    CaixaDao cdao = new CaixaDao(); 
    List<Caixa> lista= cdao.listarTodos();
    DefaultTableModel tabela =  (DefaultTableModel) jT_caixa.getModel();
    tabela.setRowCount(0);
    for(Caixa c: lista){
        tabela.addRow(new Object[]{c.getId_caixa(), c.getDataabetura_cai(), c.getDatafechamento_cai(), c.getSaldofinal_cai(), c.getSaudoinicial_cai(), c.getStatus_cai(),c.getValorcreditos_cai(),
        c.getValordebitos_cai()});
    }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCaixa dialog = new FormCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrirCaixa1;
    private javax.swing.JButton btEditar1;
    private javax.swing.JButton btExcluirCaixa1;
    private javax.swing.JButton btFecharCaixa1;
    private javax.swing.JButton btOk1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Fundo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jT_caixa;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
